### ISSUE TITLE
Package seqexec js application with FullOptJS

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#10]
Ideally the packaged javascript should be compressed and optimized with FullOptJs rather than just FastOptJS

**Comment by arturog8m** [comment]
For those of us uninitialized in these things, what is the difference between FullOptJs and FastOptJS?

**Comment by cquiroz** [comment]
These are two ways to package the js produced by scala.js. The first one `fastOptJs` which is faster to do but gives you larger js output. It is the one we have now and it is useful for development. However, for production `fullOptJs` is more appropriate giving you a much smaller js and performing several optimization. The compilation step is much slower though with `fullOptJs`
