### ISSUE TITLE
Compare upickle and boopickle for serialization

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#18]
For large objects (e.g. a sequence) the gain of binary serialization could be important, compare both approaches to check if it is worth it. We should compare having gzip compression on the backends

**Comment by cquiroz** [comment]
I ran some tests using binary serialization v/s json and for a relatively large sequence I get:

uncompressed
binary: 24689 bytes
json: 221839 bytes

We can further improve with compression, Using gzip the difference is less noticeable
binary: 1500 bytes
json: 2648 bytes

There are some costs on doing binary in terms of code complexity and human readability but still it is a nice improvement

I'd like to make binary optional if the client specify a format or a content-type

What do you think, is worth going the binary route?

**Comment by tpolecat** [comment]
I think it's worth going binary, yes. I don't see much reason to use JSON. Have you looked at scodec?

**Comment by cquiroz** [comment]
Not really, I didn't know they supported scala.js but it seems so starting on version 1.8
Do you know any particular benefit of scodec?

**Comment by cquiroz** [comment]
Json would be useful if we were going to have non-scala users, e.g. if we had operations started on the command line with curl. Perhaps that would be more important for the odb.
On the other hand we can support both. you could specify the `Accept` header or have a parameter on the url. We could use something more standard that upickle in that case, e.g. circe or argonaut

**Comment by tpolecat** [comment]
The benefit of scodec is that it's very well designed, fast, and is a Typelevel project so it's principled and will be easy to get support and participate in development if we need to contribute back. All worth considering.

**Comment by cquiroz** [comment]
I tried scodec and the binary size is not that good out of the box. I get for the same object 152234 bytes though it gzips to 2260. I suspects this happens because boopickle removes string duplicates

I got those values with  a mostly automatic derivation of codec though I had to define the codec for a few classes, nevertheless. In principle it could be improved by making our own codecs and, e.g. encode string duplicates as ints. A con is the extra work on doing this and maintaining the codecs. I suspect having our own codecs will produce less javascript code as boopickle does macro expansion instead but I didn't measure the difference

An extra burden is dependencies, the last scodec does not play nice with the last http4s so we'd need to find the proper version, in this case I only got it to work with version 1.8.0, newer versions collide

scodec works fine on scala.js

What do you think?

**Comment by cquiroz** [comment]
After giving it some thought I think I prefer boopickle. Scodec seems quite fine for established binary protocols where you need a very precise description of your format but it may require too much ceremony for our simpler case.

I see the following drawbacks in scodec:
* Produces larger payloads, I suspect this is dependent on the case and it could be due to repeating string case that is not optimized
* It adds another axis to the conficting versions of scalaz-*/shapeless/http4s
* It is likely slower in js, as boopickle is optimized for the js environment

On boopickle's case drawbacks:
* It may produce larger js as it uses macro expansions to produce picklers
* The protocol will totally change for minimal changes on the model. This is fine for our case where we only have our own client. It would be bad if we had external clients
* It would be very difficult to have non-scala clients

Any opinions?
