### ISSUE TITLE
build improvements

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/ocs3#2]
A few things I would like to add at some point are:
- [ ] [`kind-projector`](https://github.com/non/kind-projector) for simplified type-lambdas (`({ type l[a] = Either[String, a] })#l` becomes `Either[String, ?]`).
- [ ] [`sbt-header`](https://github.com/sbt/sbt-header) for maintaining consistent source file headers.
- [ ] [`wartremover`](https://github.com/puffnfresh/wartremover) for turning off things like `null` and `return`.

... probably more

**Comment by cquiroz** [comment]
I'd like to review too the scalac options, They are mostly copied from ocs but I'm not sure about their relevance

**Comment by tpolecat** [comment]
Yeah they should be cranked up as high as possible. Easy to review as we go.

**Comment by cquiroz** [comment]
Done
