### ISSUE TITLE
Upgrade libs

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#26]
Many libs have been updated since the project started

http4s to 0.13a
play to 2.5
upickle to 0.3.9
scalajs-react to 0.11.0
diode to 0.5.1
scalacss 0.4.1
React to 0.15

**Comment by tpolecat** [comment]
FYI doobie 0.3.0-SNAPSHOT is available for scalaz 7.2, scalaz-streams 0.8a, shapeless 2.3 so don't worry about moving up on those libs.

**Comment by cquiroz** [comment]
We are not importing  doobie yet, however we are dependent on spmodel, et.al, that use scalaz 7.1.6
