### ISSUE TITLE
use gh issues?

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/ocs3#3]
I realize management loves JIRA but would it be ok to use GH issues for prototyping? It's so much nicer.

**Comment by sraaphorst** [comment]
You should probably make a JIRA task to formalize this request :smiling_imp:

**Comment by arturog8m** [comment]
@tpolecat  what are the things that make GH issues so much nicer than what we get in JIRA?

**Comment by tpolecat** [comment]
- It's very simple.
- It's fast.
- It's visible to people who don't work at Gemini, in case they might want to help.
- I don't need to log into the VPN.
- It remembers my login.
- The markup language is at least somewhat standard.
- You can reference issues and PRs by number, like #2 
- You can reference commits by hash, like 6d2b05a
- You can include images inline, like

![image](https://cloud.githubusercontent.com/assets/1200131/14094646/1359640e-f50d-11e5-9e3c-4a92ed2c5d0a.png)

- You can use emoji to signal intent, like :+1: 
- It doesn't fill me with hate and make me want to set things on fire.

**Comment by swalker2m** [comment]
Having used Remedy, JIRA doesn't seem so terrible to me.  Nevertheless GH issues do seem simple, I like that it is available outside of the firewall, and I would prefer to use normal markdown instead of JIRAdown or whatever their markup is.  I vote yes on GH issues for what it is worth.  This issue is about prototype projects but if we were to switch in general it isn't clear how/whether we migrate all the existing JIRA issues.

**Comment by arturog8m** [comment]
As long as these issues are strictly relevant for software team members and won't require input from other folks at Gemini, I think this can work. So, for prototype project, sounds like a good use case and we can see how this works out. That, in addition to control @tpolecat pyromaniac tendencies of course.

**Comment by cquiroz** [comment]
Regardless of this decision we could consider opening JIRA to the world. It would help also on projects with external users like GPI, GHOST, etc

**Comment by cquiroz** [comment]
Would you be ok to add labels for issues like `Seqexec`, `build`?

**Comment by tpolecat** [comment]
@cquiroz yeah totally, we should use labels and milestones and stuff and see how it works out.
