### ISSUE TITLE
Instrument class

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#30]
The Seqexec web ui wants an `Instrument` class in lieu of the plain `String` we are using now, e.g. [here](https://github.com/gemini-hlsw/ocs3/blob/develop/modules/edu.gemini.seqexec.web/edu.gemini.seqexec.web.shared/src/main/scala/edu/gemini/seqexec/web/common/model.scala#L12)
I came up with this minimal definition

``` scala
/**
  * Representation of a Science instrument
  */
sealed trait Instrument {
  def displayName: String
}

case object GPI extends Instrument {
  override def displayName: String = "GPI"
}
case object Flamingos2 extends Instrument {
  override def displayName: String = "F2"
}
...
```

This raises the question on how to better go about this kind of general classes. OCS3 has already an `Instrument` class containing methods to run a sequence, while in OCS we have at least 4 other definitions for the science model, phase1 model, itc model, etc. We could either make a huge single `Instrument` class having all the functionality, or keep multiple `Instrument` classes per moduel, or have a single very simple class and augment the behavior for different modules as needed. I'm thinking we could have something very minimal in the common code and augment it through, e.g. implicit conversions or typeclasses

BTW I want to add a common module for these generic model class. This module should compile to both JVM and JS backends and have minimal or no dependencies

**Comment by swalker2m** [comment]
Here's an example of what I had been thinking when I was working on the new sequence model.

[Flamingos2 Instrument Example](https://github.com/swalker2m/ocs/blob/seqmod/bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/sequence/F2.scala)

Here it is relying on existing enumerations from the Java codebase as a shortcut but that isn't necessary. So an instrument is just a collection of properties that become part of the different kinds of sequence steps. I don't think I want to bog it down with responsibilities like running sequences.  As you say additional behaviors can be introduced via typeclasses.

**Comment by cquiroz** [comment]
Right, so the question is what level of complexity we want on the common `Instrument`, something as minimal as just the name is probably too low, but we don't want too many either

**Comment by tpolecat** [comment]
We should consider whether or not `Instrument` is a useful abstraction at all. Something along the lines of `Describe` in @swalker2m's prototype might say everything there is to say.
