### ISSUE TITLE
Remove argonaut dependency

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/ocs3#538]
DHS client and seqexec authentication are using argonaut. We need to switch these to use Circe.

**Comment by cquiroz** [comment]
This doesn’t bother me much, we probably have more pressing issues 😄

**Comment by cquiroz** [comment]
But feel free to send a PR if you want. We could consider switching to hhtp4s client for that

**Comment by tpolecat** [comment]
Yes, that too. Minimizing dependencies is a good use of time, especially since this one pulls in scalaz transitively.
