### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#539]
In light of the json export PR I want to throw in the alternative of using GraphQL as the standard json layout for clients

**Comment by tpolecat** [comment]
Scala implementation is https://sangria-graphql.org/

**Comment by swalker2m** [comment]
I think the experience with this has been a success and we can consider it to be the preferred solution? Can we close this issue?

**Comment by cquiroz** [comment]
Sure, @tpolecat tried and he seems to be satisfied by it, a separate issue is whether we'll use it for the front end
