### ISSUE TITLE
Use jenkins rather than travis

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#560]
We are hitting travis limits on the build and in general it is quite slow. I clock full tests in about 12 min in my laptop so we could benefit

Given @tpolecat is anyway using jenknis to do docker builds perhaps we could use it for regular buillds linked to github

WDYT?

**Comment by tpolecat** [comment]
It's easy to set up Jenkins to build by polling GH but I don't know how to set up all the hooks to make it work like Travis. So that will take some research and the propellerheads may need to open some ports.

**Comment by cquiroz** [comment]
I talked with ITS and we can use a reverse apache proxy to give access from the outside

**Comment by tpolecat** [comment]
Ok. I have no idea what that means but sounds good 👍

**Comment by sraaphorst** [comment]
Can we close this issue since we're going with buildkite?

**Comment by tpolecat** [comment]
Yep yep.
