### ISSUE TITLE
Integrate travis

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#6]
Check if it can support inbrowser-tests using selenium

**Comment by cquiroz** [comment]
I just realized that we cannot do this unless we open our repository to the internet. Is there some public mvn repo that could be used instead?

**Comment by cquiroz** [comment]
This could be a cool option [Github as a maven repo](http://kwebble.com/blog/2014/02/19/use-github-to-host-your-own-maven-repo). I'd love to avoid the grunt work of opening the repo

**Comment by tpolecat** [comment]
We could certainly publish to BinTray or Sonatype.

**Comment by cquiroz** [comment]
I got GH to work as a maven repo at [maven-repo](https://github.com/cquiroz/maven-repo)

I can see the following options as pros/cons in each case

### GitHub

**Pros**

- It is completely under our control
- We can replace RELEASE artifacts
- No need for special credentials, just make a PR

**Cons**

- Requires some manual fiddling
- Publication from ocs requires some custom changes to `build.sbt` to let it know where to publish

### Public repo (Bintray, Sonatype)

**Pros**

- Settings can be set fixed on `build.sbt`
- Straight publication, just one step from sbt

**Cons**

- More difficult to handle credentials, we must share them somehow without putting them in the github repo
- Once we publish a RELEASE we are probably stuck. That could be a problem for ocs as we don't use regularly SNAPSHOT

What do you think? I'm kind of leaning to the GH solution but I'd like to know your opinion

**Comment by cquiroz** [comment]
Here's [travis ocs3](https://travis-ci.org/cquiroz/ocs3/builds/120168978) running against the GH repo
