### ISSUE TITLE
Define a mechanism to configure applications

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#62]
system properties, configuration file

Other options:
[PureConfig](https://github.com/melrief/pureconfig)
[Ficus](https://github.com/iheartradio/ficus)
[Knobs](https://github.com/oncue/knobs)

**Comment by tpolecat** [comment]
My vote is likely to be for `Knobs` because it provides a pure interface and has a mechanism for notifying applications when the the config changes, which could be helpful.
